# Generated by Django 3.1 on 2020-08-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20200808_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingposition',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
