# Generated by Django 3.1 on 2020-08-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_auto_20200820_1539'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rankingposition',
            unique_together=set(),
        ),
    ]
