# Generated by Django 3.1 on 2020-08-31 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ranking', '0008_auto_20200831_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', through='ranking.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ranking',
            name='shares',
            field=models.ManyToManyField(blank=True, related_name='shares', through='ranking.Share', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ranking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='ranking.ranking'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
