# Generated by Django 3.1 on 2020-11-15 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ranking', '0009_auto_20200831_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ranking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_comments', to='ranking.ranking'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='content',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='image',
            field=models.ImageField(blank=True, upload_to='ranking/'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='rankingposition',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='rankingposition',
            name='image',
            field=models.ImageField(blank=True, upload_to='position/'),
        ),
        migrations.AlterField(
            model_name='rankingposition',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
