# Generated by Django 3.1 on 2020-10-14 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0010_auto_20200910_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingposition',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
