# Generated by Django 3.1 on 2020-11-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0011_rankingposition_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingposition',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='ranking',
            name='content',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='rankingposition',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='rankingposition',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
