# Generated by Django 3.1 on 2020-11-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0012_auto_20201111_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingposition',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
